KAFKA_TOPIC = "station-status"
KAFKA_BOOTSTRAP = "kafka:9092"

MINIO_ENDPOINT = "http://minio:9000"

BRONZE_BUCKET = "bronze"
SILVER_BUCKET = "silver"
GOLD_BUCKET = "gold"

EXPECTED_OBSERVATIONS_PER_HOUR = 60
EXPECTED_OBSERVATIONS_PER_DAY = EXPECTED_OBSERVATIONS_PER_HOUR * 24
